---
- name: "Apache installation using Docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml

  pre_tasks:
    - name: Download get-pip.py for Python 2.7
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
        mode: '0755'

    - name: Run get-pip.py with Python 2.7
      ansible.builtin.shell: python2.7 /tmp/get-pip.py
      args:
        creates: /usr/local/bin/pip

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker-py

  tasks:
    - name: Ensure Apache container is running
      community.docker.docker_container:
        name: webapp
        image: httpd
        state: started
        ports:
          - "80:80"