---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml

  pre_tasks:
    - name: Install EPEL repo (only for RHEL/CentOS)
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download pip script for Python 2.7
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install python-pip using get-pip.py
      ansible.builtin.command: python2.7 /tmp/get-pip.py
      args:
        creates: /usr/local/bin/pip

    - name: Install Docker Python SDK
      ansible.builtin.pip:
        name: docker-py

  tasks:
    - name: Create Apache container
      community.docker.docker_container:
        name: webapp
        image: httpd
        state: started
        ports:
          - "80:80"